# Generated by Django 6.0.3 on 2026-03-23 06:39

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, storage=config.storage_backends.ResumeStorage(), upload_to='applications/%Y/%m/%d/', verbose_name='Resume')),
                ('cover_letter_file', models.FileField(blank=True, null=True, storage=config.storage_backends.ApplicationDocumentStorage(), upload_to='cover_letters/%Y/%m/%d/', verbose_name='Cover Letter File')),
                ('cover_letter_text', models.TextField(blank=True, null=True, verbose_name='Cover Letter Text')),
                ('portfolio', models.FileField(blank=True, null=True, storage=config.storage_backends.ApplicationDocumentStorage(), upload_to='portfolios/%Y/%m/%d/', verbose_name='Portfolio')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
